# Generated by Django 5.0.6 on 2024-05-31 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studentid',
            new_name='RegNumber',
        ),
    ]
