# Generated by Django 5.0.6 on 2024-05-31 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0002_rename_studentid_student_regnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='RegNumber',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
    ]
